/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: '#fbf9fb',
        surface: '#fbf9fb',
        'surface-dim': '#dbd9db',
        'surface-bright': '#fbf9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f5',
        'surface-container': '#efedef',
        'surface-container-high': '#eae7ea',
        'surface-container-highest': '#e4e2e4',
        'surface-variant': '#e4e2e4',
        'on-surface': '#1b1b1d',
        'on-surface-variant': '#44474d',
        'inverse-surface': '#303032',
        'inverse-on-surface': '#f2f0f2',
        outline: '#75777e',
        'outline-variant': '#c5c6cd',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#0d1c32',
        'on-primary-container': '#76849f',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#b9c7e4',
        'on-primary-fixed': '#0d1c32',
        'on-primary-fixed-variant': '#39475f',
        secondary: '#5e5e5c',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdc',
        'on-secondary-container': '#636360',
        'secondary-fixed': '#e4e2de',
        'secondary-fixed-dim': '#c8c6c3',
        'on-secondary-fixed': '#1b1c1a',
        'on-secondary-fixed-variant': '#474744',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'sage-green': '#8A9A5B',
        'antique-gold': '#C5A059',
        'ink-blue': '#112240',
        'paper-shadow': '#E8E4D9',
        'alert-crimson': '#93272C',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        gutter: '24px',
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-lg': ['Playfair Display'],
        'headline-md': ['Playfair Display'],
        'headline-sm': ['Playfair Display'],
        'display-lg': ['Playfair Display'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
